import { FormEvent, useEffect, useState } from "react";
import { createClient, Session } from "@supabase/supabase-js";

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const apiUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/vihem-rental-customer-portal`;
type Data = { customer: { first_name: string; email: string }; bookings: any[]; requests: any[] };
async function call<T>(session: Session, body: Record<string, unknown>) { const response = await fetch(apiUrl, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Kundportalen kunde inte svara."); return data as T; }
const money = (value: unknown, currency = "SEK") => new Intl.NumberFormat("sv-SE", { style: "currency", currency }).format(Number(value || 0));
const label = (value: string) => ({ confirmed: "Bekräftad", active: "Pågår", completed: "Avslutad", cancelled: "Avbokad", paid: "Betald", unpaid: "Obetald", pending: "Väntar" } as Record<string, string>)[value] || value;

function Login() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); const { error } = await supabase.auth.signInWithPassword({ email, password }); setBusy(false); setMessage(error?.message || ""); } async function reset() { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/kundportal/reset-password` }); setMessage(error?.message || "Återställningslänk skickad."); } return <main className="portal-shell"><section className="portal-card"><p className="eyebrow">VIBORENT</p><h1>Kundportal</h1><p className="muted">Se dina bokningar, betalningar och kontakta oss.</p><form onSubmit={submit} className="portal-form"><label>E-post<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Lösenord<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="primary" disabled={busy}>{busy ? "Loggar in..." : "Logga in"}</button></form><button className="text-link" onClick={() => void reset()}>Glömt lösenord?</button>{message && <p className="portal-message">{message}</p>}</section></main>; }
function ResetPassword() { const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); async function submit(e: FormEvent) { e.preventDefault(); const { error } = await supabase.auth.updateUser({ password }); setMessage(error?.message || "Lösenordet är uppdaterat."); } return <main className="portal-shell"><section className="portal-card"><p className="eyebrow">VIBORENT</p><h1>Nytt lösenord</h1><form onSubmit={submit} className="portal-form"><label>Nytt lösenord<input type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="primary">Spara lösenord</button></form>{message && <p className="portal-message">{message}</p>}</section></main>; }
function Dashboard({ session }: { session: Session }) { const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [text, setText] = useState(""); const [type, setType] = useState("question"); const [busy, setBusy] = useState(false); const load = async () => { try { setData(await call<Data>(session, { action: "me" })); } catch (e) { setError(e instanceof Error ? e.message : "Kunde inte hämta portalen."); } }; useEffect(() => { void load(); }, []); async function send(e: FormEvent) { e.preventDefault(); if (!text.trim()) return; setBusy(true); try { await call(session, { action: "request", request_type: type, message: text }); setText(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Kunde inte skicka meddelandet."); } finally { setBusy(false); } } if (error) return <main className="portal-shell"><section className="portal-card"><h1>Kundportal</h1><p>{error}</p></section></main>; if (!data) return <main className="portal-shell"><p>Laddar kundportal...</p></main>; return <main className="portal-shell"><header className="portal-header"><div><p className="eyebrow">VIBORENT KUNDPORTAL</p><h1>Hej {data.customer.first_name || "där"}!</h1></div><button className="secondary" onClick={() => void supabase.auth.signOut()}>Logga ut</button></header><section className="portal-grid"><section className="portal-panel"><p className="eyebrow">ÖVERSIKT</p><h2>Mina bokningar</h2>{data.bookings.length === 0 ? <p className="muted">Du har inga bokningar ännu.</p> : data.bookings.map(booking => <article className="portal-booking" key={booking.id}><div><strong>{booking.public_reference}</strong><p>{new Date(booking.start_at).toLocaleString("sv-SE")} – {new Date(booking.end_at).toLocaleString("sv-SE")}</p></div><div><span className="portal-status">{label(booking.status)}</span><span className="portal-status">{label(booking.payment_status)}</span><strong>{money(booking.total, booking.currency)}</strong></div></article>)}</section><section className="portal-panel"><p className="eyebrow">KONTAKT</p><h2>Skicka förfrågan</h2><form onSubmit={send} className="portal-form"><select value={type} onChange={e => setType(e.target.value)}><option value="question">Fråga</option><option value="change_booking">Ändra bokning</option><option value="cancel_booking">Avboka bokning</option><option value="message">Meddelande</option></select><textarea rows={5} value={text} onChange={e => setText(e.target.value)} placeholder="Skriv ditt meddelande..." required /><button className="primary" disabled={busy}>{busy ? "Skickar..." : "Skicka"}</button></form>{data.requests.map(request => <article className="portal-request" key={request.id}><strong>{label(request.request_type)}</strong><p>{request.message}</p><span className="portal-status">{label(request.status)}</span>{request.staff_reply && <blockquote>{request.staff_reply}</blockquote>}</article>)}</section></section></main>; }
export function CustomerPortal({ reset = false }: { reset?: boolean }) { const [session, setSession] = useState<Session | null>(null); useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []); if (reset) return <ResetPassword />; return session ? <Dashboard session={session} /> : <Login />; }
