import React, { useEffect, useState } from 'react';
import { FileSearch, Mail, Paperclip, Settings, Download } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Badge, Button, Card, Input, Select, Textarea } from '../components/ui';

type Account = { id: string; email: string; display_name: string; description: string; active?: boolean; search_general?: boolean; search_invoices?: boolean; last_test_status?: string; last_test_error_code?: string };
type SearchResult = { id: string; thread_id: string; subject: string; from: string; to: string; date: string; snippet: string; score: number; has_attachments: boolean; timestamp?: number };

function mailTimestamp(value: string) { const timestamp = Date.parse(value); return Number.isNaN(timestamp) ? 0 : timestamp; }

async function invoke(body: Record<string, unknown>) {
  const { data, error } = await supabase.functions.invoke('vihem-gmail', { body });
  if (error) {
    const context = (error as { context?: Response }).context;
    const payload = context ? await context.clone().json().catch(() => null) : data;
    const detail = payload?.details ? ` (${payload.details})` : '';
    throw new Error(`${payload?.error || error.message || 'Gmail-integrationen svarade inte.'}${detail}`);
  }
  if (data?.ok === false) throw new Error(`${data.error || 'Anslutningen kunde inte verifieras.'}${data.details ? ` (${data.details})` : ''}`);
  return data;
}

export function MailPage({ onNavigate: _onNavigate }: { onNavigate: (page: string) => void }) {
  const [tab, setTab] = useState<'search' | 'settings'>('search');
  const [mode, setMode] = useState<'general' | 'invoice'>('general');
  const [query, setQuery] = useState('');
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [accountId, setAccountId] = useState('all');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [sort, setSort] = useState<'date_desc' | 'date_asc'>('date_desc');
  const [viewMode, setViewMode] = useState<'mixed' | 'grouped'>('mixed');
  const [groups, setGroups] = useState<{ account: Account; results: SearchResult[]; error: { code: string; message: string } | null }[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [configured, setConfigured] = useState(false);
  const [form, setForm] = useState({ email: '', display_name: '', description: '', search_general: true, search_invoices: true });

  const load = async () => { try { const data = await invoke({ action: 'status' }); setAccounts(data.accounts || []); setConfigured(Boolean(data.configured)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Kunde inte läsa Gmail-status.'); } };
  useEffect(() => { void load(); }, []);

  const search = async () => {
    setLoading(true); setMessage(''); setGroups([]);
    try { const data = await invoke({ action: 'search', query: query.trim(), mode, date_from: dateFrom || undefined, date_to: dateTo || undefined, sort, account_ids: accountId === 'all' ? [] : [accountId] }); setGroups(data.results || []); }
    catch (e) { setMessage(e instanceof Error ? e.message : 'Sökningen misslyckades.'); }
    finally { setLoading(false); }
  };
  const openMessage = async (account: Account, result: SearchResult) => { setLoading(true); try { const data = await invoke({ action: 'message', account_id: account.id, message_id: result.id }); setSelected({ account, ...data.message }); } catch (e) { setMessage(e instanceof Error ? e.message : 'Meddelandet kunde inte öppnas.'); } finally { setLoading(false); } };
  const download = async (attachment: any) => { if (!selected) return; try { const data = await invoke({ action: 'attachment', account_id: selected.account.id, message_id: selected.id, attachment_id: attachment.attachment_id, filename: attachment.filename, mime_type: attachment.mime_type }); const bytes = Uint8Array.from(atob(data.data_base64.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: data.mime_type })); const a = document.createElement('a'); a.href = url; a.download = data.filename; a.click(); URL.revokeObjectURL(url); } catch (e) { setMessage(e instanceof Error ? e.message : 'Bilagan kunde inte hämtas.'); } };
  const saveAccount = async () => { setLoading(true); try { const data = await invoke({ action: 'create_account', ...form }); setAccounts(data.accounts || []); setForm({ email: '', display_name: '', description: '', search_general: true, search_invoices: true }); setMessage('Mailboxen är tillagd.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Mailboxen kunde inte sparas.'); } finally { setLoading(false); } };
  const test = async (id: string) => { setLoading(true); try { const data = await invoke({ action: 'test', id }); setMessage(data.ok ? 'Anslutningen fungerar.' : data.error); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Testet misslyckades.'); } finally { setLoading(false); } };
  const renderResult = (account: Account, result: SearchResult) => <button key={`${account.id}-${result.id}`} type="button" onClick={() => void openMessage(account, result)} className="flex w-full items-start gap-3 rounded-xl border border-slate-200 p-4 text-left transition hover:border-blue-300 hover:bg-blue-50"><Mail className="mt-1 h-5 w-5 shrink-0 text-blue-600" /><span className="min-w-0 flex-1"><span className="flex flex-wrap justify-between gap-2"><strong className="truncate text-slate-900">{result.subject}</strong><span className="text-xs text-slate-500">{result.date}</span></span><span className="block text-sm text-slate-600">{result.from}</span><span className="mt-1 flex flex-wrap items-center gap-2 text-sm text-slate-500">{viewMode === 'mixed' && <Badge className="bg-blue-50 text-blue-700">{account.display_name || account.email}</Badge>}<span className="truncate">{result.snippet}</span></span></span>{result.has_attachments && <Paperclip className="h-4 w-4 text-slate-400" />}</button>;
  const mixedResults = groups.flatMap(group => group.results.map(result => ({ account: group.account, result }))).sort((a, b) => sort === 'date_asc' ? mailTimestamp(a.result.date) - mailTimestamp(b.result.date) : mailTimestamp(b.result.date) - mailTimestamp(a.result.date));

  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 pb-24">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-600">Underlag</p><h1 className="mt-2 text-3xl font-bold text-slate-950">E-post & underlag</h1><p className="mt-2 max-w-3xl text-slate-600">Sök i godkända Workspace-mailboxar och hitta fakturor, kvitton och bilagor utan att VI-HEM kan ändra eller skicka e-post.</p></div><div className="flex gap-2"><Badge className={configured ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}>{configured ? 'Google konfigurerat' : 'Google saknar serverkonfiguration'}</Badge><Button variant="secondary" onClick={() => setTab(tab === 'search' ? 'settings' : 'search')}><Settings className="h-4 w-4" />{tab === 'search' ? 'Mailboxar' : 'Sök e-post'}</Button></div></div>
    {message && <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">{message}</div>}
    {tab === 'settings' ? <>
      <Card className="p-5"><h2 className="text-lg font-bold text-slate-950">Google Workspace</h2><p className="mt-1 text-sm text-slate-500">Service account och Domain-Wide Delegation konfigureras som Supabase secrets. Här väljer admin vilka mailboxar som får sökas.</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Tillåten scope: <code>gmail.readonly</code>. Ingen skickning, radering, arkivering eller ändring av etiketter stöds.</div></Card>
      <Card className="p-5"><h2 className="text-lg font-bold text-slate-950">Lägg till mailbox</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Input label="Workspace-adress" placeholder="fakturor@vibogruppen.se" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Input label="Visningsnamn" value={form.display_name} onChange={e => setForm({ ...form, display_name: e.target.value })} /><Textarea label="Beskrivning" className="md:col-span-2" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></div><div className="mt-4 flex flex-wrap gap-4 text-sm font-semibold"><label><input type="checkbox" checked={form.search_general} onChange={e => setForm({ ...form, search_general: e.target.checked })} /> Allmän sökning</label><label><input type="checkbox" checked={form.search_invoices} onChange={e => setForm({ ...form, search_invoices: e.target.checked })} /> Fakturor/underlag</label></div><Button className="mt-4" onClick={saveAccount} loading={loading}>Lägg till mailbox</Button></Card>
      <Card className="p-5"><h2 className="text-lg font-bold text-slate-950">Godkända mailboxar</h2><div className="mt-4 space-y-3">{accounts.length === 0 && <p className="text-sm text-slate-500">Inga mailboxar är tillagda ännu.</p>}{accounts.map(account => <div key={account.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="font-bold text-slate-900">{account.display_name || account.email}</p><p className="text-sm text-slate-500">{account.email}{account.description ? ` · ${account.description}` : ''}</p></div><div className="flex items-center gap-2"><Badge className={account.last_test_status === 'ok' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}>{account.last_test_status === 'ok' ? 'Testad' : 'Ej testad'}</Badge><Button size="sm" variant="secondary" onClick={() => test(account.id)} loading={loading}>Testa</Button></div></div>)}</div></Card>
    </> : <>
      <Card className="p-5"><div className="grid gap-4 lg:grid-cols-[minmax(240px,1fr)_170px_170px_150px_150px_150px_auto]"><Input label="Sök i e-post" placeholder="t.ex. Ahlsell 837182" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && void search()} /><Select label="Läge" value={mode} options={[{ value: 'general', label: 'Allmän e-post' }, { value: 'invoice', label: 'Fakturor & underlag' }]} onChange={e => setMode(e.target.value as any)} /><Select label="Mailbox" value={accountId} options={[{ value: 'all', label: 'Alla godkända' }, ...accounts.map(a => ({ value: a.id, label: a.display_name || a.email }))]} onChange={e => setAccountId(e.target.value)} /><Input label="Från datum" type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} /><Input label="Till datum" type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} /><Select label="Sortering" value={sort} options={[{ value: 'date_desc', label: 'Nyast först' }, { value: 'date_asc', label: 'Äldst först' }]} onChange={e => setSort(e.target.value as 'date_desc' | 'date_asc')} /><Button className="mt-6" onClick={search} loading={loading}><FileSearch className="h-4 w-4" />Sök</Button></div><div className="mt-4 flex flex-wrap items-center gap-3"><Select label="Resultatvy" value={viewMode} options={[{ value: 'mixed', label: 'Alla blandade' }, { value: 'grouped', label: 'Per inkorg' }]} onChange={e => setViewMode(e.target.value as 'mixed' | 'grouped')} /><p className="text-xs text-slate-500">Lämna sökfältet tomt för att söka på datum. Resultaten sorteras efter meddelandedatum.</p></div></Card>
      {viewMode === 'mixed' ? <Card className="p-5"><div className="mb-4"><h2 className="font-bold text-slate-950">Alla inkorgar</h2><p className="text-sm text-slate-500">{mixedResults.length} träffar i vald datumordning. Inkorg visas som tagg.</p></div><div className="space-y-2">{mixedResults.length === 0 ? <p className="text-sm text-slate-500">Inga träffar.</p> : mixedResults.map(({ account, result }) => renderResult(account, result))}</div></Card> : groups.map(group => <Card key={group.account.id} className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-950">{group.account.display_name || group.account.email}</h2><p className="text-sm text-slate-500">{group.account.email}</p></div>{group.error && <Badge className="bg-red-50 text-red-700">{group.error.message}</Badge>}</div><div className="space-y-2">{group.results.length === 0 && !group.error && <p className="text-sm text-slate-500">Inga träffar.</p>}{group.results.map(result => renderResult(group.account, result))}</div></Card>)}
    </>}
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-4 sm:items-center" onClick={() => setSelected(null)}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-sm text-slate-500">{selected.from}</p><h2 className="text-xl font-bold text-slate-950">{selected.subject}</h2><p className="text-sm text-slate-500">{selected.date}</p></div><Button variant="secondary" onClick={() => setSelected(null)}>Stäng</Button></div><div className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm text-slate-800">{selected.body || selected.snippet}</div>{selected.attachments?.length > 0 && <div className="mt-5"><h3 className="font-bold text-slate-900">Bilagor</h3><div className="mt-2 space-y-2">{selected.attachments.map((a: any) => <div key={a.attachment_id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3"><span className="text-sm font-semibold">{a.filename}</span><Button size="sm" variant="secondary" onClick={() => void download(a)}><Download className="h-4 w-4" />Hämta</Button></div>)}</div></div>}<p className="mt-5 text-xs text-slate-500">Originalet ligger kvar i Gmail. VI-HEM sparar inte meddelandet permanent.</p></div></div>}
  </div>;
}
