import { createFixture } from './fixture.mjs';
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await createFixture(db);
const root = new URL('..', import.meta.url).pathname;
const migration=root+'/supabase/migrations/202610060001_vibo_website.sql';
await db.exec(fs.readFileSync(fs.existsSync(migration) ? migration : new URL('../../../supabase/migrations/20261006120000_vihem_vibofast_website.sql',import.meta.url),'utf8'));
assert.equal((await db.query('select value from other_app_data where id=1')).rows[0].value,'untouched');
const org='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002',apt='00000000-0000-4000-8000-000000000003',prop='00000000-0000-4000-8000-000000000004',tenant='00000000-0000-4000-8000-000000000005',admin='00000000-0000-4000-8000-000000000006';
await db.exec(`insert into vihem_organisations values('${org}'),('${other}');
insert into vihem_vibofast_private.site_content(id,organisation_id) values(true,'${org}');
insert into vihem_properties values('${prop}','${org}','Gatan 1','Virserum','57772',true);
insert into vihem_apartments values('${apt}','${prop}','${org}','vacant',6500,75,3,'1001','apartment');
insert into vihem_profiles values('${admin}','${org}','admin',true);`);
async function available(){return (await db.query(`select vihem_vibofast_private.available_from('${apt}','2026-10-06')::text as date`)).rows[0].date;}
assert.equal(await available(),'2026-10-06');
await db.exec(`insert into vihem_tenancies values('${tenant}','${apt}','${org}','2026-01-01',null,'active');`);
assert.equal(await available(),null,'active tenancy suppresses even a stale vacant apartment');
await db.exec(`update vihem_tenancies set status='terminated',end_date='2027-01-31';`);
assert.equal(await available(),'2027-02-01');
await db.exec(`update vihem_tenancies set end_date='2028-02-29';`);assert.equal(await available(),'2028-03-01');
await db.exec(`update vihem_tenancies set end_date='2026-12-31';`);assert.equal(await available(),'2027-01-01');
await db.exec(`update vihem_tenancies set end_date=null;`);assert.equal(await available(),null);
await db.exec(`insert into vihem_termination_requests values(gen_random_uuid(),'${tenant}','${org}','submitted','2027-01-31');`);assert.equal(await available(),null,'unconfirmed requests stay private');
await db.exec(`update vihem_termination_requests set status='approved';`);assert.equal(await available(),'2027-02-01');
const signedAgreement='00000000-0000-4000-8000-000000000007';
await db.exec(`insert into vihem_agreements values('${signedAgreement}','${org}','draft','agreement');
insert into vihem_agreement_entity_links values('${signedAgreement}','apartment','${apt}');
insert into vihem_agreement_versions values('${signedAgreement}',1,'[{"block_type":"date","content":{"label":"Tillträdesdatum","value":"2027-02-01"}}]');`);
assert.equal(await available(),'2027-02-01','a draft agreement does not reserve');
await db.exec(`update vihem_agreements set status='signed';`);assert.equal(await available(),null,'future signed lease suppresses even before tenancy creation');
await db.exec(`update vihem_agreements set status='cancelled';`);assert.equal(await available(),'2027-02-01');
await db.exec(`insert into vihem_tenancies values(gen_random_uuid(),'${apt}','${org}','2027-02-01',null,'active');`);assert.equal(await available(),null,'new tenancy hides apartment');
await db.exec(`delete from vihem_tenancies where id <> '${tenant}'; update vihem_apartments set status='renovation';`);assert.equal(await available(),null);
await db.exec(`update vihem_apartments set status='vacant',organisation_id='${other}';`);assert.equal(await available(),null,'other organisation cannot appear');
await db.exec(`update vihem_apartments set organisation_id='${org}';`);
const payload={slug:'test',title:'Test',images:['https://example.com/photo.jpg'],listingType:'apartment',leaseType:'tillsvidare',rentType:'warmhyra',description:'Description',shortDescription:'Short',features:[],utilities:{},internal_notes:'SECRET',tenant_email:'SECRET',rent:1};
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[admin]);
const initial=fs.readFileSync(root+'/integration/initial-content.json','utf8');
await db.query('select public.vihem_vibofast_save_content($1,1)',[initial]);
await assert.rejects(db.query('select public.vihem_vibofast_save_content($1,2)',[{}]),/company/);
await db.query(`select public.vihem_vibofast_save_advert($1,$2,true,0,'2027-03-01')`,[apt,payload]);
assert.equal(await available(),'2027-03-01','ready date may delay but never advance availability');
const data=(await db.query('select public.vihem_vibofast_public_site() as data')).rows[0].data;
assert.equal(data.listings.length,1);assert.equal(data.listings[0].rent,6500);assert.equal(data.listings[0].internal_notes,undefined);assert.equal(data.listings[0].tenant_email,undefined);
await assert.rejects(db.query(`select public.vihem_vibofast_save_advert($1,$2,true,0,null)`,[apt,payload]),/ändrats/);
await db.exec(`set role anon;`);
await db.query('select public.vihem_vibofast_public_site()');
await assert.rejects(db.query('select public.vihem_vibofast_admin_site()'),/permission denied/);
await assert.rejects(db.query('select * from vihem_vibofast_private.adverts'),/permission denied/);
await db.exec('reset role;');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[tenant]);
await assert.rejects(db.query('select public.vihem_vibofast_admin_site()'),/Forbidden/);
// Role-driven website access follows all active admins automatically.
const secondAdmin='00000000-0000-4000-8000-000000000008';
await db.exec(`insert into vihem_profiles values('${secondAdmin}','${org}','admin',true);`);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[secondAdmin]);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,true);
await db.exec(`update vihem_profiles set active=false where id='${secondAdmin}';`);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,false);
await db.exec(`update vihem_profiles set active=true,organisation_id='${other}' where id='${secondAdmin}';`);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,false);
await db.exec(`update vihem_profiles set organisation_id='${org}',role='staff' where id='${secondAdmin}';`);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,false);
// Install the separately deployable profile guard and verify genuine PostgreSQL role checks.
const guardPath=root+'/supabase/migrations/20261006113000_vihem_profile_authority_guard.sql';
await db.exec(fs.readFileSync(fs.existsSync(guardPath) ? guardPath : new URL('../../../supabase/migrations/20261006113000_vihem_profile_authority_guard.sql',import.meta.url),'utf8'));
await db.exec(`grant usage on schema public,auth to authenticated; grant select,insert,update on public.vihem_profiles to authenticated,service_role;
insert into vihem_profiles values('${tenant}','${other}','tenant',true); set role authenticated;`);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[tenant]);
await assert.rejects(db.query(`update vihem_profiles set role='admin' where id='${tenant}'`),/authorised administrator/);
await assert.rejects(db.query(`update vihem_profiles set organisation_id='${org}' where id='${tenant}'`),/authorised administrator/);
await assert.rejects(db.query(`update vihem_profiles set role='superadmin' where id='${tenant}'`),/authorised administrator/);
await assert.rejects(db.query(`insert into vihem_profiles values(gen_random_uuid(),'${org}','admin',true)`),/authorised administrator/);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,false);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[admin]);
await assert.rejects(db.query(`update vihem_profiles set role='admin' where id='${tenant}'`),/authorised administrator/,'admins cannot change another organisation');
await assert.rejects(db.query(`update vihem_profiles set organisation_id='${org}' where id='${tenant}'`),/authorised administrator/);
await assert.rejects(db.query(`update vihem_profiles set role='superadmin' where id='${admin}'`),/authorised administrator/);
await assert.rejects(db.query(`insert into vihem_profiles values(gen_random_uuid(),'${other}','admin',true)`),/authorised administrator/);
await assert.rejects(db.query(`insert into vihem_profiles values(gen_random_uuid(),'${org}','superadmin',true)`),/authorised administrator/);
await db.query(`insert into vihem_profiles values(gen_random_uuid(),'${org}','tenant',true)`);
await db.query(`update vihem_profiles set role='admin' where id='${secondAdmin}'`);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[secondAdmin]);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,true,'normal administrator promotion automatically grants access');
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[admin]);
await db.query(`update vihem_profiles set role='staff' where id='${secondAdmin}'`);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[secondAdmin]);
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,false,'demotion automatically removes access');
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[admin]);
await db.query(`update vihem_profiles set active=false where id='${secondAdmin}'`);
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[secondAdmin]);
await assert.rejects(db.query(`update vihem_profiles set active=true where id='${secondAdmin}'`),/authorised administrator/);
await db.exec('reset role; alter table public.vihem_profiles add column display_name text; set role authenticated;');
await db.query(`update vihem_profiles set display_name='Updated name' where id='${secondAdmin}'`);
await db.exec('reset role; set role service_role;');
await db.query(`update vihem_profiles set role='admin',active=true where id='${secondAdmin}'`);
await db.exec('reset role;');
assert.equal((await db.query('select public.vihem_vibofast_is_editor() as allowed')).rows[0].allowed,true,'existing server-only profile management remains supported');
for(let i=0;i<5;i++)await db.query(`select public.vihem_vibofast_store_enquiry('contact','{}','test')`);
await assert.rejects(db.query(`select public.vihem_vibofast_store_enquiry('contact','{}','test')`),/Rate limit/);
console.log('PASS: real PostgreSQL migrations, publication dates, organisation scope, public projection, concurrent edits, all active admins, automatic revocation, profile authority guard, server management and rate limiting.');
await db.close();
