import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role;
create schema auth; create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.vihem_organisations(id uuid primary key);
create table public.vihem_profiles(id uuid primary key,organisation_id uuid,role text,active boolean);
create table public.vihem_properties(id uuid primary key,organisation_id uuid,address text,city text,zip text,active boolean);
create table public.vihem_apartments(id uuid primary key,property_id uuid,organisation_id uuid,status text,rent numeric,size numeric,rooms numeric,apartment_number text,unit_type text);
create table public.vihem_tenancies(id uuid primary key,apartment_id uuid,organisation_id uuid,start_date date,end_date date,status text);
create table public.vihem_termination_requests(id uuid primary key,tenancy_id uuid,organisation_id uuid,status text,requested_move_out_date date);
create table public.vihem_agreements(id uuid primary key,organisation_id uuid,status text,document_type text);
create table public.vihem_agreement_entity_links(agreement_id uuid,entity_type text,entity_id uuid);
create table public.vihem_agreement_versions(agreement_id uuid,version_number integer,blocks jsonb);
create table public.other_app_data(id integer primary key,value text); insert into other_app_data values(1,'untouched');
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid,bucket_id text); alter table storage.objects enable row level security;
`);
const root = new URL('..', import.meta.url).pathname;
const migration=root+'/supabase/migrations/202610060001_vibo_website.sql';
await db.exec(fs.readFileSync(fs.existsSync(migration) ? migration : new URL('../../../supabase/migrations/20261006120000_vihem_vibofast_website.sql',import.meta.url),'utf8'));
assert.equal((await db.query('select value from other_app_data where id=1')).rows[0].value,'untouched');
const org='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002',apt='00000000-0000-4000-8000-000000000003',prop='00000000-0000-4000-8000-000000000004',tenant='00000000-0000-4000-8000-000000000005',admin='00000000-0000-4000-8000-000000000006';
await db.exec(`insert into vihem_organisations values('${org}'),('${other}');
insert into vihem_vibofast_private.site_content(id,organisation_id) values(true,'${org}');
insert into vihem_properties values('${prop}','${org}','Gatan 1','Virserum','57772',true);
insert into vihem_apartments values('${apt}','${prop}','${org}','vacant',6500,75,3,'1001','apartment');
insert into vihem_profiles values('${admin}','${org}','admin',true);`);
async function available(){return (await db.query(`select vihem_vibofast_private.available_from('${apt}','2026-10-06')::text as date`)).rows[0].date;}
assert.equal(await available(),'2026-10-06');
await db.exec(`insert into vihem_tenancies values('${tenant}','${apt}','${org}','2026-01-01',null,'active');`);
assert.equal(await available(),null,'active tenancy suppresses even a stale vacant apartment');
await db.exec(`update vihem_tenancies set status='terminated',end_date='2027-01-31';`);
assert.equal(await available(),'2027-02-01');
await db.exec(`update vihem_tenancies set end_date='2028-02-29';`);assert.equal(await available(),'2028-03-01');
await db.exec(`update vihem_tenancies set end_date='2026-12-31';`);assert.equal(await available(),'2027-01-01');
await db.exec(`update vihem_tenancies set end_date=null;`);assert.equal(await available(),null);
await db.exec(`insert into vihem_termination_requests values(gen_random_uuid(),'${tenant}','${org}','submitted','2027-01-31');`);assert.equal(await available(),null,'unconfirmed requests stay private');
await db.exec(`update vihem_termination_requests set status='approved';`);assert.equal(await available(),'2027-02-01');
const signedAgreement='00000000-0000-4000-8000-000000000007';
await db.exec(`insert into vihem_agreements values('${signedAgreement}','${org}','draft','agreement');
insert into vihem_agreement_entity_links values('${signedAgreement}','apartment','${apt}');
insert into vihem_agreement_versions values('${signedAgreement}',1,'[{"block_type":"date","content":{"label":"Tillträdesdatum","value":"2027-02-01"}}]');`);
assert.equal(await available(),'2027-02-01','a draft agreement does not reserve');
await db.exec(`update vihem_agreements set status='signed';`);assert.equal(await available(),null,'future signed lease suppresses even before tenancy creation');
await db.exec(`update vihem_agreements set status='cancelled';`);assert.equal(await available(),'2027-02-01');
await db.exec(`insert into vihem_tenancies values(gen_random_uuid(),'${apt}','${org}','2027-02-01',null,'active');`);assert.equal(await available(),null,'new tenancy hides apartment');
await db.exec(`delete from vihem_tenancies where id <> '${tenant}'; update vihem_apartments set status='renovation';`);assert.equal(await available(),null);
await db.exec(`update vihem_apartments set status='vacant',organisation_id='${other}';`);assert.equal(await available(),null,'other organisation cannot appear');
await db.exec(`update vihem_apartments set organisation_id='${org}';`);
const payload={slug:'test',title:'Test',images:['https://example.com/photo.jpg'],listingType:'apartment',leaseType:'tillsvidare',rentType:'warmhyra',description:'Description',shortDescription:'Short',features:[],utilities:{},internal_notes:'SECRET',tenant_email:'SECRET',rent:1};
await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[admin]);
const initial=fs.readFileSync(root+'/integration/initial-content.json','utf8');
await db.query('select public.vihem_vibofast_save_content($1,1)',[initial]);
await assert.rejects(db.query('select public.vihem_vibofast_save_content($1,2)',[{}]),/company/);
await db.query(`select public.vihem_vibofast_save_advert($1,$2,true,0,'2027-03-01')`,[apt,payload]);
assert.equal(await available(),'2027-03-01','ready date may delay but never advance availability');
const data=(await db.query('select public.vihem_vibofast_public_site() as data')).rows[0].data;
assert.equal(data.listings.length,1);assert.equal(data.listings[0].rent,6500);assert.equal(data.listings[0].internal_notes,undefined);assert.equal(data.listings[0].tenant_email,undefined);
await assert.rejects(db.query(`select public.vihem_vibofast_save_advert($1,$2,true,0,null)`,[apt,payload]),/ändrats/);
await db.exec(`set role anon;`);
await db.query('select public.vihem_vibofast_public_site()');
await assert.rejects(db.query('select public.vihem_vibofast_admin_site()'),/permission denied/);
await assert.rejects(db.query('select * from vihem_vibofast_private.adverts'),/permission denied/);
await db.exec('reset role;');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[tenant]);
await assert.rejects(db.query('select public.vihem_vibofast_admin_site()'),/Forbidden/);
for(let i=0;i<5;i++)await db.query(`select public.vihem_vibofast_store_enquiry('contact','{}','test')`);
await assert.rejects(db.query(`select public.vihem_vibofast_store_enquiry('contact','{}','test')`),/Rate limit/);
console.log('PASS: real PostgreSQL migration, vacancy, notice, dates, new tenancy, blocking, organisation scope, public field projection, concurrent edits, permissions, rate limiting.');
await db.close();
